services:
  db:
    image: "postgres:17"
    restart: "unless-stopped"
    environment:
      POSTGRES_USER: "myappUser"
      POSTGRES_PASSWORD: "myappPass"
      POSTGRES_DB: "myappDB"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
