import { db } from "@/lib/db";
import { EventStatus, EventType } from "../../generated";

const eventsData = [
  {
    clientName: "Monika Rusin",
    eventDate: new Date("12-12-2026"),
    startTime: "15:00",
    endTime: "03:00",
    eventPlace: "Zajazd pod gruszą",
    title: "Wesele Moniki & Adama",
    guestCount: 150,
    partner1Name: "Monika Rusin",
    partner2Name: "Jakub Domański",
    eventType: EventType.Wedding,
  },
  {
    clientName: "Magdalena Adamczyk",
    eventDate: new Date("2026-05-23"),
    startTime: "16:00",
    endTime: "04:00",
    eventPlace: "Dwór Pod Lipami, Niepołomice",
    title: "Wesele Magdaleny & Piotra",
    guestCount: 130,
    phone: "692447015",
    partner1Name: "Magdalena Adamczyk",
    partner2Name: "Piotr Lewandowski",
    notes: "Pierwszy taniec: walc angielski. Oczepiny o północy.",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Katarzyna Zając",
    eventDate: new Date("2026-06-20"),
    startTime: "17:00",
    endTime: "03:00",
    eventPlace: "Stara Stodoła, Zabierzów",
    title: "Wesele Katarzyny & Michała",
    guestCount: 90,
    partner1Name: "Katarzyna Zając",
    partner2Name: "Michał Kowalczyk",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Łukasz Górecki",
    eventDate: new Date("2026-07-18"),
    endTime: "00:00",
    eventPlace: "Restauracja Nad Stawem",
    title: "25. rocznica ślubu Góreckich",
    partner1Name: "Ewa Górecka",
    partner2Name: "Marek Górecki",
    eventType: EventType.Anniversary,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Joanna Kaczmarek",
    eventDate: new Date("2026-08-29"),
    startTime: "18:00",
    endTime: "02:00",
    eventPlace: "Klub Piwnica, Kraków",
    title: "18. urodziny Oli",
    guestCount: 45,
    phone: "664318204",
    notes: "Bez disco polo. Dużo muzyki z lat 2000.",
    eventType: EventType.Birthday_18,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Krzysztof Sikora",
    eventDate: new Date("2026-09-05"),
    startTime: "20:00",
    endTime: "23:30",
    eventPlace: "Rynek, scena plenerowa",
    title: "Dni Miasta - scena taneczna",
    phone: "733170971",
    notes: "Odwołane przez organizatora z powodu pogody.",
    eventType: EventType.Festival,
    eventStatus: EventStatus.Cancelled,
  },
  {
    clientName: "Paweł Majewski",
    eventDate: new Date("2026-09-11"),
    startTime: "19:00",
    endTime: "01:00",
    eventPlace: "Hotel Panorama, sala bankietowa",
    title: "Jubileusz 10-lecia firmy",
    guestCount: 80,
    eventType: EventType.Corporate_Event,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Dawid Lis",
    eventDate: new Date("2026-11-06"),
    startTime: "09:00",
    endTime: "17:00",
    eventPlace: "Centrum Konferencyjne Młyn",
    title: "Konferencja branżowa - oprawa muzyczna",
    phone: "551281837",
    notes: "Potrzebne 2 mikrofony bezprzewodowe i nagłośnienie sali.",
    eventType: EventType.Conference,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Alex Nowak",
    eventDate: new Date("2026-11-28"),
    startTime: "20:00",
    endTime: "03:00",
    eventPlace: "Klub Piwnica, Kraków",
    title: "Impreza andrzejkowa",
    guestCount: 60,
    eventType: EventType.Other,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Paweł Majewski",
    eventDate: new Date("2026-12-18"),
    startTime: "18:00",
    endTime: "00:00",
    eventPlace: "Hotel Panorama, sala bankietowa",
    title: "Wigilia firmowa",
    guestCount: 120,
    notes: "Pierwsza godzina tylko kolędy i muzyka w tle.",
    eventType: EventType.Corporate_Event,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Natalia Baran",
    eventDate: new Date("2027-01-23"),
    startTime: "19:00",
    endTime: "04:00",
    eventPlace: "Dwór Pod Lipami, Niepołomice",
    title: "Studniówka klas maturalnych",
    guestCount: 220,
    notes: "Polonez o 19:30 - własne nagranie od szkoły.",
    eventType: EventType.Prom,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Aleksandra Kubiak",
    eventDate: new Date("2027-03-06"),
    endTime: "01:00",
    eventPlace: "Restauracja Nad Stawem",
    title: "18. urodziny Aleksandry",
    guestCount: 30,
    eventType: EventType.Birthday_18,
  },
  {
    clientName: "Zuzanna Michalska",
    eventDate: new Date("2027-06-19"),
    startTime: "16:30",
    endTime: "04:00",
    eventPlace: "Stara Stodoła, Zabierzów",
    title: "Wesele Zuzanny & Kacpra",
    guestCount: 140,
    phone: "608923561",
    partner1Name: "Zuzanna Michalska",
    partner2Name: "Kacper Zieliński",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Agnieszka Wróbel",
    eventDate: new Date("2027-08-21"),
    endTime: "04:00",
    eventPlace: "Do ustalenia",
    title: "Wesele Agnieszki",
    partner1Name: "Agnieszka Wróbel",
    eventType: EventType.Wedding,
  },
  {
    clientName: "Karolina Wieczorek",
    eventDate: new Date("2027-09-11"),
    endTime: "03:00",
    eventPlace: "Pałacyk Leśny",
    title: "Wesele Karoliny & Marcina",
    partner1Name: "Karolina Wieczorek",
    partner2Name: "Marcin Pietrzak",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Tomasz Nowicki",
    eventDate: new Date("2026-04-25"),
    startTime: "16:00",
    endTime: "03:00",
    eventPlace: "Dwór Zieleniec",
    title: "Wesele Tomasza & Ewy",
    guestCount: 110,
    partner1Name: "Ewa Malinowska",
    partner2Name: "Tomasz Nowicki",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Weronika Dudek",
    eventDate: new Date("2026-05-09"),
    startTime: "18:00",
    endTime: "01:00",
    eventPlace: "Klub Forty, Kraków",
    title: "18. urodziny Weroniki",
    guestCount: 50,
    eventType: EventType.Birthday_18,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Michał Pawlak",
    eventDate: new Date("2026-06-06"),
    startTime: "17:00",
    endTime: "04:00",
    eventPlace: "Pałac Goetz, Brzesko",
    title: "Wesele Michała & Kingi",
    guestCount: 160,
    phone: "559155133",
    partner1Name: "Kinga Sowa",
    partner2Name: "Michał Pawlak",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Sebastian Czarnecki",
    eventDate: new Date("2026-07-04"),
    startTime: "19:00",
    endTime: "23:00",
    eventPlace: "Bulwary Wiślane, scena letnia",
    title: "Letni festiwal nad Wisłą",
    notes: "Set 120-128 BPM, house i nu-disco.",
    eventType: EventType.Festival,
    eventStatus: EventStatus.Completed,
  },
  {
    clientName: "Julia Kołodziej",
    eventDate: new Date("2026-08-15"),
    startTime: "16:00",
    endTime: "03:00",
    eventPlace: "Zajazd pod gruszą",
    title: "Wesele Julii & Szymona",
    guestCount: 95,
    partner1Name: "Julia Kołodziej",
    partner2Name: "Szymon Sowa",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Cancelled,
    notes: "Para przełożyła ślub na kolejny rok.",
  },
  {
    clientName: "Anna Lewandowska",
    eventDate: new Date("2026-10-17"),
    startTime: "19:00",
    endTime: "02:00",
    eventPlace: "Hotel Panorama, sala bankietowa",
    title: "40. urodziny Anny",
    guestCount: 70,
    phone: "602341778",
    eventType: EventType.Other,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Piotr Zieliński",
    eventDate: new Date("2026-10-24"),
    startTime: "09:00",
    endTime: "16:00",
    eventPlace: "ICE Kraków, sala B",
    title: "TechConf Polska - oprawa muzyczna",
    phone: "698117420",
    notes: "Muzyka w przerwach + intro prelegentów.",
    eventType: EventType.Conference,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Kamil Mazur",
    eventDate: new Date("2026-11-14"),
    startTime: "20:00",
    endTime: "02:00",
    eventPlace: "Restauracja Wierzynek",
    title: "Impreza firmowa Mazur Logistics",
    guestCount: 85,
    eventType: EventType.Corporate_Event,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Martyna Krawczyk",
    eventDate: new Date("2027-01-16"),
    startTime: "19:00",
    endTime: "04:00",
    eventPlace: "Pałacyk Leśny",
    title: "Studniówka II LO",
    guestCount: 180,
    phone: "791604215",
    eventType: EventType.Prom,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Magdalena Adamczyk",
    eventDate: new Date("2027-05-22"),
    startTime: "18:00",
    endTime: "01:00",
    eventPlace: "Dwór Pod Lipami, Niepołomice",
    title: "1. rocznica ślubu Magdaleny & Piotra",
    guestCount: 40,
    partner1Name: "Magdalena Adamczyk",
    partner2Name: "Piotr Lewandowski",
    eventType: EventType.Anniversary,
  },
  {
    clientName: "Mateusz Król",
    eventDate: new Date("2027-05-29"),
    endTime: "04:00",
    eventPlace: "Do ustalenia",
    title: "Wesele Mateusza & Oliwii",
    partner1Name: "Oliwia Szymańska",
    partner2Name: "Mateusz Król",
    eventType: EventType.Wedding,
  },
  {
    clientName: "Emilia Kaczmarek",
    eventDate: new Date("2027-06-26"),
    startTime: "16:00",
    endTime: "03:00",
    eventPlace: "Stara Stodoła, Zabierzów",
    title: "Wesele Emilii & Adama",
    guestCount: 120,
    phone: "600523645",
    partner1Name: "Emilia Kaczmarek",
    partner2Name: "Adam Wójcik",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Patrycja Sobczak",
    eventDate: new Date("2027-07-10"),
    startTime: "18:00",
    endTime: "02:00",
    eventPlace: "Klub Piwnica, Kraków",
    title: "18. urodziny Patrycji",
    guestCount: 40,
    eventType: EventType.Birthday_18,
  },
  {
    clientName: "Adrian Jasiński",
    eventDate: new Date("2027-08-07"),
    startTime: "17:00",
    endTime: "04:00",
    eventPlace: "Dwór Zieleniec",
    title: "Wesele Adriana & Moniki",
    guestCount: 150,
    phone: "555218485",
    partner1Name: "Monika Lis",
    partner2Name: "Adrian Jasiński",
    eventType: EventType.Wedding,
    eventStatus: EventStatus.Active,
  },
  {
    clientName: "Alicja Nowak",
    eventDate: new Date("2027-09-25"),
    endTime: "00:00",
    eventPlace: "Restauracja Nad Stawem",
    title: "30. rocznica ślubu Nowaków",
    partner1Name: "Alicja Nowak",
    partner2Name: "Jerzy Nowak",
    eventType: EventType.Anniversary,
  },
];

async function seedingEventsData() {
  if (!process.env.DATABASE_URL?.includes("localhost")) {
    throw new Error("Process can't be run on production");
  }

  const clients = await db.client.findMany({ select: { id: true, name: true } });

  const eventsDataWithClientId = eventsData.map(({ clientName, ...event }) => {
    const client = clients.find((el) => el.name === clientName);

    if (!client) {
      throw new Error(`Client "${clientName}" not found`);
    }

    return { ...event, clientId: client.id };
  });

  await db.event.deleteMany();

  const events = await db.event.createMany({ data: eventsDataWithClientId });

  console.log(events);
}

seedingEventsData()
  .then(async () => {
    await db.$disconnect();
  })
  .catch(async (err) => {
    console.error(err);
    await db.$disconnect();
    process.exit(1);
  });
